### PR TITLE
Fix incorrect parsing and printing micro- and nanoseconds

### LINKED ISSUE #23: Wrong parsing and printing if format contains micro- or nanoseconds
If you parse something and format contains micro- or nanoseconds, only three digits are parsed as nanoseconds:
```
> timeParse [Format_NanoSecond] "123456789"
Just (DateTime {dtDate = Date {dateYear = 0, dateMonth = January, dateDay = 0}, dtTime = TimeOfDay {todHour = 0h, todMin = 0m, todSec = 0s, todNSec = 123ns}})
> timeParse [Format_MicroSecond] "123456"
Just (DateTime {dtDate = Date {dateYear = 0, dateMonth = January, dateDay = 0}, dtTime = TimeOfDay {todHour = 0h, todMin = 0m, todSec = 0s, todNSec = 123000ns}})
```

Similarly, `timePrint` print only three digits:
```
> timePrint [Format_NanoSecond] $ DateTime { dtDate = Date { dateYear=0, dateMonth=January, dateDay=0}, dtTime = TimeOfDay { todHour=0, todMin=0, todSec=0, todNSec=NanoSeconds 123456789}}
"789"
> timePrint [Format_MicroSecond] $ DateTime { dtDate = Date { dateYear=0, dateMonth=January, dateDay=0}, dtTime = TimeOfDay { todHour=0, todMin=0, todSec=0, todNSec=NanoSeconds 123456789}}
"456"
```

### PR DESCRIPTION
**Pull request by gltronred**
Fixes #23 

Should I change something in this PR? Please tell me, because I'm not very familiar with pull requests and GitHub

### CODE REVIEW

**Comment by vincenthz** [comment]
IIRC, printing the nanoseconds is only about printing the nanoseconds part below the microseconds. I appreciate that one might expect the other behavior of printing everything to the nanosecond precisions.

Also just notice that the documentation disagree with the code, so definitely bad.

parsing and printing code is expecting to get/set things in mask of 3 digits, whereas documentation says
nanoseconds is 0 to 9999999999, microseconds is 0 to 999999, ...

**Comment by vincenthz** [comment]
your PR is really good btw, adding tests is definitely the right thing to do. In the light on my comment, would you like to undo the change to the parsing/printing and make your test works ?

BTW, to print sub seconds, you should use the Format_Precision n (9 for ns, 6 for us, 3 for ms), Format_{Milli,Micro,Nano}Seconds are used for parsing or printing such format `23s 100ms 200us`

**Comment by gltronred** [comment]
OK, I will change parsing/printing and documentation about Format_{Micro,Nano}Seconds.

To clarify, is it true that [Format_Precision 9] should work the same way as [Format_MilliSeconds, Format_MicroSeconds, Format_NanoSeconds]?

**Comment by vincenthz** [comment]
Thanks you !

about the question, yes. potentially have also the same properties with 6=Ms+Us and 3=Ms too.

**Comment by vincenthz** [comment]
archiving repository

**Pull request closed without merging**
